task.spawn(function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/lovelyang/roblox/main/func.lua"))()
        end)
task.spawn(function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/lovelyang/roblox/main/load.lua"))()
        end)
